### ISSUE TITLE
ERROR: cannot launch node of type [baxter_mpnet/remap.py]: baxter_mpnet

### ISSUE THREAD

**Issue by watashihageteru** [anthonysimeonov/baxter_mpnet_experiments#2]
Hi!
when i launched the baxter_mpnet by the following command,

             roslaunch baxter_mpnet_experiments baxter_mpnet.launch

the folowing error was occured.

ERROR: cannot launch node of type [baxter_mpnet/remap.py]: baxter_mpnet
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/minoya/ros_ws/src/moveit_robots/atlas_moveit_config
ROS path [2]=/home/minoya/ros_ws/src/moveit_robots/atlas_v3_moveit_config
ROS path [3]=/home/minoya/ros_ws/src/baxter_common/baxter_common
ROS path [4]=/home/minoya/ros_ws/src/baxter_common/baxter_core_msgs
ROS path [5]=/home/minoya/ros_ws/src/baxter_common/baxter_description
ROS path [6]=/home/minoya/ros_ws/src/baxter_simulator/baxter_gazebo
ROS path [7]=/home/minoya/ros_ws/src/moveit_robots/baxter/baxter_ikfast_left_arm_plugin
ROS path [8]=/home/minoya/ros_ws/src/moveit_robots/baxter/baxter_ikfast_right_arm_plugin
ROS path [9]=/home/minoya/ros_ws/src/baxter_interface
ROS path [10]=/home/minoya/ros_ws/src/baxter_examples
ROS path [11]=/home/minoya/ros_ws/src/baxter_common/baxter_maintenance_msgs
ROS path [12]=/home/minoya/ros_ws/src/baxter/baxter_sdk
ROS path [13]=/home/minoya/ros_ws/src/baxter_simulator/baxter_sim_controllers
ROS path [14]=/home/minoya/ros_ws/src/baxter_simulator/baxter_sim_io
ROS path [15]=/home/minoya/ros_ws/src/baxter_simulator/baxter_sim_kinematics
ROS path [16]=/home/minoya/ros_ws/src/baxter_simulator/baxter_sim_hardware
ROS path [17]=/home/minoya/ros_ws/src/baxter_simulator/baxter_simulator
ROS path [18]=/home/minoya/ros_ws/src/baxter_tools
ROS path [19]=/home/minoya/ros_ws/src/baxter_moveit_experiments
ROS path [20]=/home/minoya/ros_ws/src/baxter_mpnet_experiments
ROS path [21]=/home/minoya/ros_ws/src/moveit_robots/iri_wam_moveit_config
ROS path [22]=/home/minoya/ros_ws/src/moveit_robots/moveit_robots
ROS path [23]=/home/minoya/ros_ws/src/moveit_robots/r2_moveit_generated
ROS path [24]=/home/minoya/ros_ws/src/baxter_common/rethink_ee_description
ROS path [25]=/home/minoya/ros_ws/src/moveit_robots/baxter/baxter_moveit_config
ROS path [26]=/home/minoya/ros_ws/src/baxter_simulator/baxter_sim_examples
ROS path [27]=/home/minoya/ros_ws/src/warehouse_ros
ROS path [28]=/home/minoya/ros_ws/src/warehouse_ros_mongo
ROS path [29]=/opt/ros/kinetic/share

there is no file named "remap.py" in the baxter_mpnet_experiments 's directory.
is there any solution to solved it?

**Comment by AnujAgrawal7** [comment]
I am also getting a similar error message. 

ERROR: cannot launch node of type [baxter_mpnet/remap.py]: baxter_mpnet
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/anuj07/ros_ws/src
ROS path [2]=/opt/ros/kinetic/share
process[move_group-17]: started with pid [23553]
process[rviz_AnujTheGreat_23399_8672619700574446079-18]: started with pid [23555]
ERROR: cannot launch node of type [warehouse_ros_mongo/mongo_wrapper_ros.py]: warehouse_ros_mongo
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/anuj07/ros_ws/src
ROS path [2]=/opt/ros/kinetic/share

How did you solve it?
